CREATE TABLE `techtrade` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `skill_code` varchar(500) DEFAULT NULL,
  `company_code` varchar(500) DEFAULT NULL,
  `company_name` varchar(500) DEFAULT NULL,
  `skilltype_code` varchar(500) DEFAULT NULL,
  `skilltype_name` varchar(500) DEFAULT NULL,
  `skill_name` varchar(500) DEFAULT NULL,
  `register_date` varchar(500) DEFAULT NULL,
  `keyword` varchar(500) DEFAULT NULL,
  `skill_detail` varchar(4000) DEFAULT NULL,
  `dev_state` varchar(500) DEFAULT NULL,
  `apply_field` varchar(500) DEFAULT NULL,
  `developer_company` varchar(500) DEFAULT NULL,
  `developer_phone` varchar(500) DEFAULT NULL,
  `patent_number` varchar(500) DEFAULT NULL,
  `invent_name` varchar(500) DEFAULT NULL,
  `research_name` varchar(500) DEFAULT NULL,
  `institution_name` varchar(500) DEFAULT NULL,
  `skill_lifetime` varchar(500) DEFAULT NULL,
  `location` varchar(30) DEFAULT NULL,
  `url` varchar(500) DEFAULT NULL,
  `u` varchar(11) DEFAULT NULL,
  `x` varchar(11) DEFAULT NULL,
  `y` varchar(11) DEFAULT NULL,
  `z` varchar(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;